[client]
showSidebarNavigation = true

[logger]
level = "info"

[theme]
primaryColor = "#0D4F45"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font = "sans serif"
